### PR TITLE
ppull

### PR DESCRIPTION
**Pull request by RanveerHothi24**

### CODE REVIEW

**Comment by RanveerHothi24** [comment]
p

**Review by RanveerHothi24 — COMMENTED** [review]
abc

**Comment by RanveerHothi24** [comment]
hovering on shirts

**Review by RanveerHothi24 — COMMENTED** [review]
hovering on shirts

**Review by RanveerHothi24 — COMMENTED** [review]
Scrolling down on pressing sign up button

**Review by RanveerHothi24 — COMMENTED** [review]
jump to cs page on shirt click

**Review by meno2003 — APPROVED** [review]

**Pull request merged**
